-- Run as ACCOUNTADMIN (or an admin role)
CREATE ROLE IF NOT EXISTS BALANCEIQ_ROLE;
GRANT ROLE BALANCEIQ_ROLE TO ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS BALANCEIQ_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE BALANCEIQ_WH TO ROLE BALANCEIQ_ROLE;

CREATE DATABASE IF NOT EXISTS BALANCEIQ_DB;
CREATE SCHEMA IF NOT EXISTS BALANCEIQ_DB.CORE;

GRANT USAGE ON DATABASE BALANCEIQ_DB TO ROLE BALANCEIQ_ROLE;
GRANT USAGE ON SCHEMA BALANCEIQ_DB.CORE TO ROLE BALANCEIQ_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA BALANCEIQ_DB.CORE TO ROLE BALANCEIQ_ROLE;

USE ROLE BALANCEIQ_ROLE;
USE WAREHOUSE BALANCEIQ_WH;
USE DATABASE BALANCEIQ_DB;
USE SCHEMA CORE;